on: [push]
 
name: test
 
jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
 
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
 
      - name: Run fmt
        run: forge fmt --check

      - name: Run lint
        run: forge lint

      - name: Run build
        run: forge clean && forge build
      