[profile.default]
src = "contracts"
out = "out"
viaIR = true
libs = ["node_modules", "lib"]
test = "foundry/test"
script = "foundry/script"
cache_path = "cache_forge"
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
ffi = true
evm_version = "paris"

fs_permissions = [
  { access = "read", path = "./" }
]

[lint]
exclude_lints = [
  "unaliased-plain-import", 
  "mixed-case-variable", 
  "mixed-case-function", 
  "pascal-case-struct", 
  "screaming-snake-case-immutable",
  "unwrapped-modifier-logic",
  "unsafe-typecast"
]
