profile = "default"

[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "foundry/test"
cache_path = "cache_forge"
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
ffi = true

fs_permissions = [
  { access = "read", path = "./" }
]

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
]


